# This is a basic workflow to help you get started with Actions

name: Push To Main Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel    
jobs:
  steps:
    uses: revlitix/java-service-workflow/.github/workflows/push-to-main.yml@main
    secrets:
      PACKAGE_PUBLISH_TOKEN: ${{ secrets.PACKAGE_PUBLISH_TOKEN }}
      PACKAGE_PUBLISH_USERNAME: ${{ secrets.PACKAGE_PUBLISH_USERNAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PACKAGE_PUBLISH_USERNAME }}
